name: CI

on: pull_request

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  rubocop:
    name: Rubocop
    uses: theforeman/actions/.github/workflows/rubocop.yml@v1
    with:
      ruby: 3.0
      additional_packages: 
        - 'libkrb5-dev'
        - 'libldap-dev' 
        - 'libsasl2-dev'
